packages:
  - 'packages/tansolid'
  - 'packages/__tests__/implementation'

allowBuilds:
  '@parcel/watcher': true
  esbuild: true

nodeLinker: hoisted

minimumReleaseAge: 300

minimumReleaseAgeExclude:
  - '@bemedev/codebase@1.3.0'
  - '@bemedev/dev-utils@0.8.3'
