/**
 * List of warnings to avoid in the console.
 *
 * Add here any warning message (or part of it) that you want to avoid in the console.
 *
 * Do not edit this file unless you know what you are doing.
 *
 * @see {@link console}
 */
export const AVOIDED_WARNINGS = [
  'computations created outside a `createRoot` or `render` will never be disposed',
];
