/**
 *
 * This file overrides the default console.warn function to filter out specific warning messages.
 * It checks if the warning message contains any of the predefined substrings in the AVOIDED_WARNINGS array.
 * If a match is found, the warning is suppressed; otherwise, it is logged to the console as usual.
 *
 * Do not edit this file unless you know what you are doing.
 *
 * But you can add more warnings to avoid in the `AVOIDED_WARNINGS` array in the `warn.avoid.ts` file.
 *
 * @see {@link AVOIDED_WARNINGS}
 * @see {@link console}
 */

import { AVOIDED_WARNINGS } from './warn.avoid';

const originalWarn = console.warn;

console.warn = function (...args: any[]) {
  const message = args.join(' ');
  const check = !AVOIDED_WARNINGS.some(warning =>
    message.includes(warning),
  );
  if (check) originalWarn(...args);
};
